# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: sling

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/flarco/dbio' go.mod
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./cmd/sling
    
    env:
      - CGO_ENABLED=1

    goarch:
      - amd64
      # - '386'
      # - arm64
      # - arm
    # goarm:
    #   - '6'
    #   - '7'
    goos:
      - linux
    ldflags:
      - "-X 'github.com/slingdata-io/sling-cli/core.Version={{.Version}}' -X 'github.com/slingdata-io/sling-cli/core/env.RudderstackKey={{.Env.RUDDERSTACK_KEY}}'"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

snapshot:
  name_template: "{{ incpatch .Version }}"

checksum:
  name_template: '{{ .Runtime.Goos }}.{{ .Runtime.Goarch }}.checksums.txt'

dockers:
  - dockerfile: 'cmd/sling/Dockerfile'
    image_templates:
    - "slingdata/sling:latest"
    - "slingdata/sling:{{ .Tag }}"

# mc policy set public DO/ocral/slingdata.io/cli
blobs:
  - provider: s3
    endpoint: https://nyc3.digitaloceanspaces.com
    bucket: ocral
    folder: "slingdata.io/dist/{{.Version}}"
    region: nyc3

release:
  mode: replace
  header: |
    ## Sling {{ .Tag }} ({{ .Date }})